name: Job Scraper

on:
  workflow_dispatch:       # تشغيل يدوي
  schedule:
    - cron: "0 */12 * * *" # تشغيل كل 12 ساعة

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/jobs.json
          git commit -m "Update jobs data"
          git push
